import Navbar from "@/components/Layout/Navbar";
import Sidebar from "@/components/Layout/Sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <div className="min-h-screen flex flex-col">
          <Navbar className="fixed top-0 left-0 right-0 z-50 h-16" />
          <div className="flex flex-1 pt-16">
            <Sidebar/>
            <div className="w-full overflow-x-auto bg-blue-50">
              <div className="sm:h-[calc(99vh-60px)] overflow-auto">
                <div className="w-full flex overflow-auto h-[calc(100vh-110px)] overflow-y-auto relative">
                  <div className="w-full m-5">
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}
